export const Datos = [
    {
        id: 1,
        img: require('../assets/juice.jpg'),
        name: 'Valentino',
        apellido: 'Villella',
        seguidores: 100000,
        texto: 'lorem ipsum hurnfub uushv0soiwh wphgowehwuego wuwiuegfweifg jygfwieofhwoef wiefhwoefwuoe wiugwuefwoi lorem ipsum hurnfub uushv0soiwh wphgowehwuego wuwiuegfweifg jygfwieofhwoef wiefhwoefwuoe wiugwuefwoi lorem ipsum hurnfub uushv0soiwh wphgowehwuego wuwiuegfweifg jygfwieofhwoef wiefhwoefwuoe wiugwuefwoi',
    },
    {
        id: 2,
        img: require('../assets/juice.jpg'),
        name: 'Augusto',
        apellido: 'Villella',
        seguidores: 134000,
        texto: 'lorem ipsum hurnfub uushv0soiwh wphgowehwuego wuwiuegfweifg jygfwieofhwoef wiefhwoefwuoe wiugwuefwoi',
    },
    {
        id: 3,
        img: require('../assets/juice.jpg'),
        name: 'Lorenzo',
        apellido: 'Villella',
        seguidores: 134000,
        texto: 'lorem ipsum hurnfub uushv0soiwh wphgowehwuego wuwiuegfweifg jygfwieofhwoef wiefhwoefwuoe wiugwuefwoi',
    },
    {
        id: 4,
        img: require('../assets/juice.jpg'),
        name: 'Maria Elena',
        apellido: 'Osso',
        seguidores: 134000,
        texto: 'lorem ipsum hurnfub uushv0soiwh wphgowehwuego wuwiuegfweifg jygfwieofhwoef wiefhwoefwuoe wiugwuefwoi',
    },
    {
        id: 5,
        img: require('../assets/juice.jpg'),
        name: 'Fiamma',
        apellido: 'Alcorta',
        seguidores: 134000,
        texto: 'lorem ipsum hurnfub uushv0soiwh wphgowehwuego wuwiuegfweifg jygfwieofhwoef wiefhwoefwuoe wiugwuefwoi',
    },
    {
        id: 6,
        img: require('../assets/juice.jpg'),
        name: 'Elian',
        apellido: 'Lemos',
        seguidores: 134000,
        texto: 'lorem ipsum hurnfub uushv0soiwh wphgowehwuego wuwiuegfweifg jygfwieofhwoef wiefhwoefwuoe wiugwuefwoi',
    },
    {
        id: 7,
        img: require('../assets/juice.jpg'),
        name: 'Daniel',
        apellido: 'Deleo',
        seguidores: 134000,
        texto: 'lorem ipsum hurnfub uushv0soiwh wphgowehwuego wuwiuegfweifg jygfwieofhwoef wiefhwoefwuoe wiugwuefwoi',
    },
    {
        id: 8,
        img: require('../assets/juice.jpg'),
        name: 'Joaquin',
        apellido: 'Calul',
        seguidores: 134000,
        texto: 'lorem ipsum hurnfub uushv0soiwh wphgowehwuego wuwiuegfweifg jygfwieofhwoef wiefhwoefwuoe wiugwuefwoi',
    },
    {
        id: 9,
        img: require('../assets/juice.jpg'),
        name: 'Esteban',
        apellido: 'Araya',
        seguidores: 134000,
        texto: 'lorem ipsum hurnfub uushv0soiwh wphgowehwuego wuwiuegfweifg jygfwieofhwoef wiefhwoefwuoe wiugwuefwoi',
    },

] 